using AutoMapper;
using QLDV_KiemNghiem_BE.Data;
using QLDV_KiemNghiem_BE.Interfaces;
using QLDV_KiemNghiem_BE.Interfaces.ManagerInterface;
using QLDV_KiemNghiem_BE.Models;
using QLDV_KiemNghiem_BE.Services;

namespace QLDV_KiemNghiem_BE.Repositories
{
    public class RepositoryManager : IRepositoryManager
    {
        private readonly DataContext _context;
        private readonly Lazy<IPhieuDangKyRepository> _phieuDangKy;
        private readonly Lazy<IPhieuDangKyMauRepository> _phieuDangKyMau;
        private readonly Lazy<IPhieuDangKyPhuLieuHoaChatRepository> _phieuDangKyPhuLieuHoaChat;
        private readonly Lazy<IDmPhuLieuHoaChatRepository> _dmPhuLieuHoaChat;
        private readonly Lazy<ITieuChuanRepository> _tieuChuan;
        private readonly Lazy<IChiTieuRepositoty> _chiTieu;
        private readonly Lazy<IPhuongPhapRepository> _phuongPhap;
        private readonly Lazy<IBoPhanRepository> _boPhan;
        private readonly Lazy<IKhoaRepository> _khoa;
        private readonly Lazy<IChucVuRepository> _chucVu;
        private readonly Lazy<IPhieuDangKyMauHinhAnhRepository> _phieuDangKyMauHinhAnh;
        private readonly Lazy<ILoaiMauRepository> _loaiMau;
        private readonly Lazy<ILoaiDichVuRepository> _loaiDichVu;
        private readonly Lazy<IDmMauRepository> _dmMau;
        private readonly Lazy<ITrangThaiPhieuDkRepository> _trangThaiPhieuDk;
        private readonly Lazy<IHoaDonThuRepository> _hoaDonThu;
        private readonly Lazy<IChiTietHoaDonThuRepository> _chiTietHoaDonThu;
        private readonly Lazy<IPhieuDeXuatPhongBanRepository> _phieuDeXuatPhongBan;
        private readonly Lazy<IPhanCongNoiBoRepository> _phanCongNoiBo;
        private readonly Lazy<IPhieuDuTruRepository> _phieuDuTru;
        private readonly Lazy<IPhieuLuuMauRepository> _phieuLuuMau;
        private readonly Lazy<IPhieuTienDoLamViecRepository> _phieuTienDoLamViec;
        private readonly Lazy<IPhieuPhanTichKetQuaRepository> _phieuPhanTichKetQua;
        private readonly Lazy<IKhachHangRepository> _khachHang;
        private readonly Lazy<INhanVienRepository> _nhanVien;
        private readonly Lazy<IPhieuChiRepository> _phieuChi;
        private readonly Lazy<IPhieuPhanTichKetQuaChiTietRepository> _phieuPhanTichKetQuaChiTiet;
        private readonly Lazy<IPhieuThuRepository> _phieuThu;
        private readonly Lazy<IChiTietPhieuDeXuatPhongBanRepository> _chiTietPhieuDeXuatPhongBan;
        private readonly Lazy<ILichSuPhanCongRepository> _lichSuPhanCong;
        private readonly Lazy<IChiTietPhieuDuTruRepository> _chiTietPhieuDuTru;
        private readonly Lazy<IHoaDonThuBoSungRepository> _hoaDonThuBoSung;
        private readonly Lazy<IChiTietHoaDonThuBoSungRepository> _chiTietHoaDonThuBoSung;
        private readonly Lazy<ILichSuPhanCongMauChoKhoaRepository> _lichSuPhanCongMauChoKhoa;
        public RepositoryManager(DataContext dataContext, IMapper mapper)
        {
            _context = dataContext;
            _phieuDangKy = new Lazy<IPhieuDangKyRepository>(() => new PhieuDangKyRepository(dataContext, mapper));
            _phieuDangKyMau = new Lazy<IPhieuDangKyMauRepository>(() => new PhieuDangKyMauRepository(dataContext, mapper));
            _phieuDangKyPhuLieuHoaChat = new Lazy<IPhieuDangKyPhuLieuHoaChatRepository>(() => new PhieuDangKyPhuLieuHoaChatRepository(dataContext, mapper));
            _dmPhuLieuHoaChat = new Lazy<IDmPhuLieuHoaChatRepository>(() => new DmPhuLieuHoaChatRepository(dataContext, mapper));
            _tieuChuan = new Lazy<ITieuChuanRepository>(() => new TieuChuanRepository(dataContext, mapper));
            _chiTieu = new Lazy<IChiTieuRepositoty>(() => new ChiTieuRepository(dataContext, mapper));
            _phuongPhap = new Lazy<IPhuongPhapRepository>(() => new PhuongPhapRepository(dataContext, mapper));
            _boPhan = new Lazy<IBoPhanRepository>(() => new BoPhanRepository(dataContext, mapper));
            _khoa = new Lazy<IKhoaRepository>(() => new KhoaRepository(dataContext, mapper));
            _chucVu = new Lazy<IChucVuRepository>(() => new ChucVuRepository(dataContext, mapper));
            _phieuDangKyMauHinhAnh = new Lazy<IPhieuDangKyMauHinhAnhRepository>(() => new PhieuDangKyMauHinhAnhRepository(dataContext, mapper));
            _loaiMau = new Lazy<ILoaiMauRepository>(() => new LoaiMauRepository(dataContext, mapper));
            _loaiDichVu = new Lazy<ILoaiDichVuRepository>(() => new LoaiDichVuRepository(dataContext, mapper));
            _dmMau = new Lazy<IDmMauRepository>(() => new DmMauRepository(dataContext, mapper));
            _trangThaiPhieuDk = new Lazy<ITrangThaiPhieuDkRepository>(() => new TrangThaiPhieuDkRepository(dataContext, mapper));
            _hoaDonThu = new Lazy<IHoaDonThuRepository>(() => new HoaDonThuRepository(dataContext, mapper));
            _chiTietHoaDonThu = new Lazy<IChiTietHoaDonThuRepository>(() => new ChiTietHoaDonThuRepository(dataContext, mapper));
            _phieuDeXuatPhongBan = new Lazy<IPhieuDeXuatPhongBanRepository>(() => new PhieuDeXuatPhongBanRepository(dataContext, mapper));
            _phanCongNoiBo = new Lazy<IPhanCongNoiBoRepository>(() => new PhanCongNoiBoRepository(dataContext, mapper));
            _phieuDuTru = new Lazy<IPhieuDuTruRepository>(() => new PhieuDuTruRepository(dataContext, mapper));
            _phieuLuuMau = new Lazy<IPhieuLuuMauRepository>(() => new PhieuLuuMauRepository(dataContext, mapper));
            _phieuTienDoLamViec = new Lazy<IPhieuTienDoLamViecRepository>(() => new PhieuTienDoLamViecRepository(dataContext, mapper));
            _phieuPhanTichKetQua = new Lazy<IPhieuPhanTichKetQuaRepository>(() => new PhieuPhanTichKetQuaRepository(dataContext, mapper));
            _khachHang = new Lazy<IKhachHangRepository>(() => new KhachHangRepository(dataContext, mapper));
            _nhanVien = new Lazy<INhanVienRepository>(() => new NhanVienRepository(dataContext, mapper));
            _phieuChi = new Lazy<IPhieuChiRepository>(() => new PhieuChiRepository(dataContext, mapper));
            _phieuPhanTichKetQuaChiTiet = new Lazy<IPhieuPhanTichKetQuaChiTietRepository>(() => new PhieuPhanTichKetQuaChiTietRepository(dataContext, mapper));
            _phieuThu = new Lazy<IPhieuThuRepository>(() => new PhieuThuRepository(dataContext, mapper));
            _chiTietPhieuDeXuatPhongBan = new Lazy<IChiTietPhieuDeXuatPhongBanRepository>(() => new ChiTietPhieuDeXuatPhongBanRepository(dataContext, mapper));
            _lichSuPhanCong= new Lazy<ILichSuPhanCongRepository>(() => new LichSuPhanCongRepository(dataContext, mapper));
            _chiTietPhieuDuTru = new Lazy<IChiTietPhieuDuTruRepository>(() => new ChiTietPhieuDuTruRepository(dataContext, mapper));
            _hoaDonThuBoSung= new Lazy<IHoaDonThuBoSungRepository>(() => new HoaDonThuBoSungRepository(dataContext, mapper));
            _chiTietHoaDonThuBoSung = new Lazy<IChiTietHoaDonThuBoSungRepository>(() => new ChiTietHoaDonThuBoSungRepository(dataContext, mapper));
            _lichSuPhanCongMauChoKhoa = new Lazy<ILichSuPhanCongMauChoKhoaRepository>(() => new LichSuPhanCongMauChoKhoaRepository(dataContext, mapper));
        }

        public IPhieuDangKyRepository PhieuDangKy => _phieuDangKy.Value;
        public IPhieuDangKyMauRepository PhieuDangKyMau => _phieuDangKyMau.Value;
        public IPhieuDangKyPhuLieuHoaChatRepository PhieuDangKyPhuLieuHoaChat => _phieuDangKyPhuLieuHoaChat.Value;
        public IDmPhuLieuHoaChatRepository DmPhuLieuHoaChat => _dmPhuLieuHoaChat.Value;
        public ITieuChuanRepository TieuChuan => _tieuChuan.Value;
        public IChiTieuRepositoty ChiTieu => _chiTieu.Value;
        public IPhuongPhapRepository PhuongPhap => _phuongPhap.Value;
        public IBoPhanRepository BoPhan => _boPhan.Value;
        public IKhoaRepository Khoa => _khoa.Value;
        public IChucVuRepository ChucVu => _chucVu.Value;
        public IPhieuDangKyMauHinhAnhRepository PhieuDangKyMauHinhAnh => _phieuDangKyMauHinhAnh.Value;
        public ILoaiMauRepository LoaiMau => _loaiMau.Value;
        public ILoaiDichVuRepository LoaiDichVu => _loaiDichVu.Value;
        public IDmMauRepository DmMau => _dmMau.Value;
        public ITrangThaiPhieuDkRepository TrangThaiPhieuDk => _trangThaiPhieuDk.Value;
        public IHoaDonThuRepository HoaDonThu => _hoaDonThu.Value;
        public IChiTietHoaDonThuRepository ChiTietHoaDonThu => _chiTietHoaDonThu.Value;
        public IPhieuDeXuatPhongBanRepository PhieuDeXuatPhongBan => _phieuDeXuatPhongBan.Value;
        public IPhanCongNoiBoRepository PhanCongNoiBo => _phanCongNoiBo.Value;
        public IPhieuDuTruRepository PhieuDuTru => _phieuDuTru.Value;
        public IPhieuLuuMauRepository PhieuLuuMau => _phieuLuuMau.Value;
        public IPhieuTienDoLamViecRepository PhieuTienDoLamViec => _phieuTienDoLamViec.Value;
        public IPhieuPhanTichKetQuaRepository PhieuPhanTichKetQua => _phieuPhanTichKetQua.Value;
        public IKhachHangRepository KhachHang => _khachHang.Value;
        public INhanVienRepository NhanVien => _nhanVien.Value;
        public IPhieuChiRepository PhieuChi  => _phieuChi.Value;
        public IPhieuPhanTichKetQuaChiTietRepository PhieuPhanTichKetQuaChiTiet => _phieuPhanTichKetQuaChiTiet.Value;
        public IPhieuThuRepository PhieuThu => _phieuThu.Value;
        public IChiTietPhieuDeXuatPhongBanRepository ChiTietPhieuDeXuatPhongBan => _chiTietPhieuDeXuatPhongBan.Value;
        public ILichSuPhanCongRepository LichSuPhanCong => _lichSuPhanCong.Value;
        public IChiTietPhieuDuTruRepository ChiTietPhieuDuTru => _chiTietPhieuDuTru.Value;
        public IHoaDonThuBoSungRepository HoaDonThuBoSung => _hoaDonThuBoSung.Value;
        public IChiTietHoaDonThuBoSungRepository ChiTietHoaDonThuBoSung => _chiTietHoaDonThuBoSung.Value;
        public ILichSuPhanCongMauChoKhoaRepository LichSuPhanCongMauChoKhoa => _lichSuPhanCongMauChoKhoa.Value;
        public async Task<bool> SaveChangesAsync() => await _context.SaveChangesAsync() > 0;
    }
}
